CREATE TABLE "delay_measurements" (
	"id" serial PRIMARY KEY NOT NULL,
	"run_id" bigint NOT NULL,
	"client_id" bigint NOT NULL,
	"timestamp" timestamp NOT NULL,
	"delay" real NOT NULL
);
--> statement-breakpoint
CREATE TABLE "performance_metrics" (
	"id" serial PRIMARY KEY NOT NULL,
	"run_id" bigint NOT NULL,
	"timestamp" timestamp NOT NULL,
	"gpu_utilization" real NOT NULL,
	"working_set_private" real NOT NULL,
	"cpu_usage" real NOT NULL,
	"bytes_received" real NOT NULL,
	"bytes_sent" real NOT NULL,
	"packets_received" real NOT NULL,
	"packets_sent" real NOT NULL,
	"nv_gpu_power" real,
	"nv_gpu_temp" real,
	"nv_gpu_mem_temp" real,
	"nv_gpu_sm" real,
	"nv_gpu_mem" real,
	"nv_gpu_enc" real,
	"nv_gpu_dec" real,
	"nv_gpu_jpg" real,
	"nv_gpu_ofa" real,
	"nv_gpu_mem_clock" real,
	"nv_gpu_clock" real
);
--> statement-breakpoint
CREATE TABLE "runs" (
	"id" serial PRIMARY KEY NOT NULL,
	"game" text NOT NULL,
	"clients" bigint NOT NULL,
	"width" bigint NOT NULL,
	"height" bigint NOT NULL,
	"duration" bigint NOT NULL,
	"audio" boolean NOT NULL,
	"frame_rate" bigint NOT NULL,
	"hardware" boolean NOT NULL,
	"timestamp" timestamp NOT NULL,
	"game_started_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "webrtc_audio_metrics" (
	"id" serial PRIMARY KEY NOT NULL,
	"run_id" bigint NOT NULL,
	"client_id" bigint NOT NULL,
	"timestamp" timestamp NOT NULL,
	"ssrc" bigint,
	"kind" text,
	"transport_id" text,
	"codec_id" text,
	"codec" text,
	"jitter" real,
	"packets_lost" bigint,
	"playout_id" text,
	"track_identifier" text,
	"mid" bigint,
	"remote_id" text,
	"packets_received" bigint,
	"packets_received_per_s" real,
	"packets_discarded" bigint,
	"packets_discarded_per_s" real,
	"fec_packets_received" bigint,
	"fec_packets_received_per_s" real,
	"fec_packets_discarded" bigint,
	"fec_packets_discarded_per_s" real,
	"bytes_received" bigint,
	"bytes_received_in_bits_per_s" real,
	"header_bytes_received" bigint,
	"header_bytes_received_in_bits_per_s" real,
	"last_packet_received_timestamp" text,
	"jitter_buffer_delay" real,
	"jitter_buffer_delay_per_jitter_buffer_emitted_count_in_ms" real,
	"jitter_buffer_target_delay" real,
	"jitter_buffer_target_delay_per_jitter_buffer_emitted_count_in_ms" real,
	"jitter_buffer_minimum_delay" real,
	"jitter_buffer_minimum_delay_per_jitter_buffer_emitted_count_in_ms" real,
	"jitter_buffer_emitted_count" bigint,
	"total_samples_received" bigint,
	"total_samples_received_per_s" real,
	"concealed_samples" bigint,
	"concealed_samples_per_s" real,
	"concealed_samples_per_total_samples_received" real,
	"silent_concealed_samples" bigint,
	"silent_concealed_samples_per_s" real,
	"concealment_events" bigint,
	"inserted_samples_for_deceleration" bigint,
	"inserted_samples_for_deceleration_per_s" real,
	"removed_samples_for_acceleration" bigint,
	"removed_samples_for_acceleration_per_s" real,
	"audio_level" real,
	"total_audio_energy" real,
	"audio_level_in_rms" real,
	"total_samples_duration" real,
	"total_processing_delay" real,
	"total_processing_delay_per_jitter_buffer_emitted_count_in_ms" real,
	"jitter_buffer_flushes" bigint,
	"delayed_packet_outage_samples" bigint,
	"relative_packet_arrival_delay" real,
	"interruption_count" bigint,
	"total_interruption_duration" real
);
--> statement-breakpoint
CREATE TABLE "webrtc_candidate_pair_metrics" (
	"id" serial PRIMARY KEY NOT NULL,
	"run_id" bigint NOT NULL,
	"client_id" bigint NOT NULL,
	"timestamp" timestamp NOT NULL,
	"transport_id" text,
	"local_candidate_id" text,
	"remote_candidate_id" text,
	"state" text,
	"priority" bigint,
	"nominated" boolean,
	"writable" boolean,
	"packets_sent" bigint,
	"packets_sent_per_s" real,
	"bytes_sent" bigint,
	"bytes_sent_in_bits_per_s" real,
	"packets_received" bigint,
	"packets_received_per_s" real,
	"bytes_received" bigint,
	"bytes_received_in_bits_per_s" real,
	"total_round_trip_time" real,
	"total_round_trip_time_per_responses_received" real,
	"current_round_trip_time" real,
	"available_outgoing_bitrate" real,
	"requests_received" bigint,
	"requests_sent" bigint,
	"responses_received" bigint,
	"responses_sent" bigint,
	"consent_requests_sent" bigint,
	"packets_discarded_on_send" bigint,
	"bytes_discarded_on_send" bigint,
	"last_packet_received_timestamp" text,
	"last_packet_sent_timestamp" text
);
--> statement-breakpoint
CREATE TABLE "webrtc_data_metrics" (
	"id" serial PRIMARY KEY NOT NULL,
	"run_id" bigint NOT NULL,
	"client_id" bigint NOT NULL,
	"timestamp" timestamp NOT NULL,
	"label" text,
	"protocol" text,
	"data_channel_identifier" bigint,
	"state" text,
	"messages_sent" bigint,
	"messages_sent_per_s" real,
	"bytes_sent" bigint,
	"bytes_sent_in_bits_per_s" real,
	"messages_received" bigint,
	"messages_received_per_s" real,
	"bytes_received" bigint,
	"bytes_received_in_bits_per_s" real
);
--> statement-breakpoint
CREATE TABLE "webrtc_video_metrics" (
	"id" serial PRIMARY KEY NOT NULL,
	"run_id" bigint NOT NULL,
	"client_id" bigint NOT NULL,
	"timestamp" timestamp NOT NULL,
	"ssrc" bigint,
	"kind" text,
	"transport_id" text,
	"codec_id" text,
	"codec" text,
	"jitter" real,
	"packets_lost" bigint,
	"track_identifier" text,
	"mid" bigint,
	"packets_received" bigint,
	"packets_received_per_s" real,
	"bytes_received" bigint,
	"bytes_received_in_bits_per_s" real,
	"header_bytes_received" bigint,
	"header_bytes_received_in_bits_per_s" real,
	"retransmitted_packets_received" bigint,
	"retransmitted_packets_received_per_s" real,
	"retransmitted_bytes_received" bigint,
	"retransmitted_bytes_received_in_bits_per_s" real,
	"rtx_ssrc" bigint,
	"last_packet_received_timestamp" text,
	"jitter_buffer_delay" real,
	"jitter_buffer_delay_per_jitter_buffer_emitted_count_in_ms" real,
	"jitter_buffer_target_delay" real,
	"jitter_buffer_target_delay_per_jitter_buffer_emitted_count_in_ms" real,
	"jitter_buffer_minimum_delay" real,
	"jitter_buffer_minimum_delay_per_jitter_buffer_emitted_count_in_ms" real,
	"jitter_buffer_emitted_count" bigint,
	"frames_received" bigint,
	"frames_received_per_s" real,
	"frame_width" bigint,
	"frame_height" bigint,
	"frames_per_second" bigint,
	"frames_decoded" bigint,
	"frames_decoded_per_s" real,
	"key_frames_decoded" bigint,
	"key_frames_decoded_per_s" real,
	"frames_dropped" bigint,
	"total_decode_time" real,
	"total_decode_time_per_frames_decoded_in_ms" real,
	"total_processing_delay" real,
	"total_processing_delay_per_jitter_buffer_emitted_count_in_ms" real,
	"total_assembly_time" real,
	"total_assembly_time_per_frames_assembled_from_multiple_packets" real,
	"frames_assembled_from_multiple_packets" bigint,
	"total_inter_frame_delay" real,
	"total_inter_frame_delay_per_frames_decoded_in_ms" real,
	"total_squared_inter_frame_delay" real,
	"inter_frame_delay_st_dev_in_ms" real,
	"pause_count" bigint,
	"total_pauses_duration" real,
	"freeze_count" bigint,
	"total_freezes_duration" real,
	"decoder_implementation" text,
	"fir_count" bigint,
	"pli_count" bigint,
	"nack_count" bigint,
	"goog_timing_frame_info" text,
	"power_efficient_decoder" boolean,
	"min_playout_delay" real
);
--> statement-breakpoint
ALTER TABLE "delay_measurements" ADD CONSTRAINT "delay_measurements_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "performance_metrics" ADD CONSTRAINT "performance_metrics_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webrtc_audio_metrics" ADD CONSTRAINT "webrtc_audio_metrics_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webrtc_candidate_pair_metrics" ADD CONSTRAINT "webrtc_candidate_pair_metrics_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webrtc_data_metrics" ADD CONSTRAINT "webrtc_data_metrics_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webrtc_video_metrics" ADD CONSTRAINT "webrtc_video_metrics_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_delay_measurements_run_id" ON "delay_measurements" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "idx_delay_measurements_timestamp" ON "delay_measurements" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "idx_performance_metrics_run_id" ON "performance_metrics" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "idx_performance_metrics_timestamp" ON "performance_metrics" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "idx_webrtc_audio_metrics_run_id" ON "webrtc_audio_metrics" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "idx_webrtc_audio_metrics_timestamp" ON "webrtc_audio_metrics" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "idx_webrtc_candidate_pair_metrics_run_id" ON "webrtc_candidate_pair_metrics" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "idx_webrtc_candidate_pair_metrics_timestamp" ON "webrtc_candidate_pair_metrics" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "idx_webrtc_data_metrics_run_id" ON "webrtc_data_metrics" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "idx_webrtc_data_metrics_timestamp" ON "webrtc_data_metrics" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "idx_webrtc_video_metrics_run_id" ON "webrtc_video_metrics" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "idx_webrtc_video_metrics_timestamp" ON "webrtc_video_metrics" USING btree ("timestamp");